### ISSUE TITLE
unable to search license number

### ISSUE THREAD

**Issue by alexduros** [defeo/ffbb-api#1]
I tried it with mine but failed with that error 

```
$ ./ffbb licence -n Duros -p Alexandre
undefined:1

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request._callback (/Users/aduros/Projects/defeo/ffbb-api/ffbb:75:24)
    at Request.self.callback (/Users/aduros/Projects/defeo/ffbb-api/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/aduros/Projects/defeo/ffbb-api/node_modules/request/request.js:1082:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/aduros/Projects/defeo/ffbb-api/node_modules/request/request.js:1009:12)
    at emitNone (events.js:72:20)
```

Issues with node version number ? Mine is v4.1.1.

**Comment by defeo** [comment]
I doubt it's node's version. The syntax error happens in the html parser, that means that ffbb returned an empty document (which it always does when the request is not well formed).

I pushed a fix this morning. Have you pulled since?

**Comment by alexduros** [comment]
Aerf. My bad. This one fixed it !
